experiment:
  fig_save: true
  num_instances: 1
  parameter_matching: all
parameters:
  Plasticity.homeostasis_depression_rate:
    dtype: float
    enabled: false
    max: 1.0
    min: 0.8
    step: 0.025
  Plasticity.lambda_h:
    dtype: float
    enabled: true
    max: 0.024
    min: 0.004
    step: 0.002
  Plasticity.lambda_minus:
    dtype: float
    enabled: true
    max: 0.004
    min: 0.0005
    step: 0.0005
  Plasticity.lambda_plus:
    dtype: float
    enabled: true
    max: 0.14
    min: 0.02
    step: 0.01
  Plasticity.target_rate_h:
    dtype: float
    enabled: false
    max: 0.16
    min: 0.01
    step: 0.01
  Plasticity.tau_plus:
    dtype: int
    enabled: false
    max: 20
    min: 10
    step: 1
  Synapses.p_exc_exc:
    dtype: float
    enabled: false
    max: 0.002
    min: 0.001
    step: 0.0005
