experiment:
  fig_save: true
  num_instances: 10
  order_randomization: true
  parameter_matching: all
  seed_offset: 0
parameters:
  plasticity.homeostasis_depression_rate:
    dtype: float
    enabled: false
    max: 1.0
    min: 0.8
    step: 0.025
  plasticity.lambda_h:
    dtype: float
    enabled: true
    max: 0.03
    min: 0.01
    step: 0.005
  plasticity.lambda_minus:
    dtype: float
    enabled: true
    max: 0.005
    min: 0.003
    step: 0.0005
  plasticity.lambda_plus:
    dtype: float
    enabled: true
    max: 0.17
    min: 0.13
    step: 0.01
  plasticity.target_rate_h:
    dtype: float
    enabled: false
    max: 0.28
    min: 0.08
    step: 0.4
  plasticity.tau_plus:
    dtype: int
    enabled: true
    max: 22
    min: 15
    step: 1
  synapses.p_exc_exc:
    dtype: float
    enabled: false
    max: 0.002
    min: 0.001
    step: 0.0005
