backend: {}
calibration:
  correlation_amplitude: 1.5
  correlation_time_constant: 30
  padi_bus_dacen_extension: 9
  v_rest_calib: 275
config_type: network
encoding:
  dt_seq: 0.6
  dt_stm: 0.02
  num_repetitions: 100
  t_exc_start: 0.015
  t_scaling_factor: 0.001
experiment:
  episodes: 50
  generate_rand_seed_offset: false
  id: no-calib_on-chip
  log_permanence: true
  log_weights: true
  run_add_calib: false
  runtime: 128.00000000000009
  save_auto: false
  save_auto_epoches: 5
  save_final: false
  seed_offset: 0
  sequences:
  - - A
    - C
    - B
  - - D
    - C
    - B
  type: opt-grid
network:
  num_neurons: 15
  num_symbols: 4
  pattern_size: 4
neurons:
  dendrite:
    I_p: 120
    tau_dAP: 30
    theta_dAP: 140
  excitatory:
    tau_m:
    - 10
    - 10
    tau_refrac:
    - 30
    - 5
    tau_syn_E:
    - 2
    - 5
    tau_syn_I:
    - 3
    - 1
    v_reset:
    - 120
    - 60
    v_rest:
    - 80
    - 60
    v_thresh:
    - 140
    - 120
  inhibitory:
    tau_m: 2
    tau_refrac: 15
    tau_syn_E: 0.5
    tau_syn_I: 1
    v_reset: 60
    v_rest: 60
    v_thresh: 70
performance:
  compute_performance: true
  method: all_symbols
  running_avgs:
  - 0.25
  - 0.5
  - 0.75
  - 1.0
plasticity:
  correlation_threshold: 70
  delta_t_max: 0.038
  delta_t_min: 0.002
  dt: 0.0001
  execution_interval: 80.0
  execution_start: 78.0
  lambda_h: 10
  lambda_minus: 0.006
  lambda_plus: 16
  learning_factor: 1.0
  permanence_init_max: 5
  permanence_init_min: 5
  permanence_max: 20.0
  permanence_threshold: 40
  target_rate_h: 100
  tau_h: 1.28
  tau_plus: 0.01
  type: original
  w_mature: 50
  weight_learning: false
  weight_learning_scale: 1
  y: 1
plotting:
  file_type: pdf
  save_figure: true
  size:
  - 10
  - 12
synapses:
  delay_exc_exc: 0.0
  delay_exc_inh: 0.0
  delay_ext_exc: 0.0
  delay_inh_exc: 0.0
  dyn_inh_weights: true
  dyn_weight_calculation: false
  p_exc_exc: 0.44999999999999996
  receptor_exc_exc: excitatory
  receptor_exc_inh: excitatory
  receptor_ext_exc: excitatory
  receptor_inh_exc: inhibitory
  w_exc_exc: 0.0
  w_exc_inh: 45
  w_ext_exc: 52
  w_inh_exc: -400
