experiment:
  fig_save: true
  num_instances: 1
  order_randomization: true
  parameter_matching: all
  plot_perf_dd: true
  seed_offset: 0
parameters:
  plasticity.correlation_threshold:
    dtype: int
    enabled: true
    max: 90
    min: 70
    step: 10
  plasticity.lambda_h:
    dtype: int
    enabled: true
    max: 16
    min: 8
    step: 2
  plasticity.lambda_minus:
    dtype: float
    enabled: false
    max: 0.008
    min: 0.004
    step: 0.002
  plasticity.lambda_plus:
    dtype: int
    enabled: true
    max: 18
    min: 14
    step: 2
  plasticity.permanence_threshold:
    dtype: int
    enabled: true
    max: 80
    min: 40
    step: 20
  plasticity.target_rate_h:
    dtype: int
    enabled: true
    max: 100
    min: 60
    step: 20
  synapses.p_exc_exc:
    dtype: float
    enabled: false
    max: 0.4
    min: 0.3
    step: 0.05
  synapses.w_exc_inh:
    dtype: int
    enabled: false
    max: 50
    min: 30
    step: 5
  synapses.w_ext_exc:
    dtype: float
    enabled: false
    max: 58
    min: 46
    step: 2
  synapses.w_inh_exc:
    dtype: float
    enabled: false
    max: -280
    min: -360
    step: 10
